version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php_container
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    networks:
      - app_network
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - php

  mysql:
    image: mysql:5.7
    env_file: .env
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

networks:
  app_network:

volumes:
  mysql_data:
